-- JS Reddit Growth OS - Supabase Schema 
-- Exact Match to Local Dexie DB 

DROP TABLE IF EXISTS performances, tasks, assets, subreddits, accounts, models, settings CASCADE;

CREATE TABLE models (
    "id" BIGINT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "status" TEXT,
    "primaryNiche" TEXT,
    "weeklyViewTarget" INTEGER,
    "weeklyPostTarget" INTEGER,
    "driveFolderId" TEXT,
    "usedFolderId" TEXT,
    "redgifsProfile" TEXT,
    "proxyInfo" TEXT,
    "vaPin" TEXT
);

CREATE TABLE accounts (
    "id" BIGINT PRIMARY KEY,
    "modelId" BIGINT REFERENCES models("id") ON DELETE CASCADE,
    "handle" TEXT NOT NULL,
    "status" TEXT,
    "dailyCap" INTEGER,
    "cqsStatus" TEXT,
    "removalRate" FLOAT,
    "totalKarma" INTEGER,
    "linkKarma" INTEGER,
    "commentKarma" INTEGER,
    "createdUtc" FLOAT,
    "isSuspended" BOOLEAN,
    "lastSyncDate" TEXT,
    "notes" TEXT,
    "proxyInfo" TEXT
);

CREATE TABLE subreddits (
    "id" BIGINT PRIMARY KEY,
    "modelId" BIGINT REFERENCES models("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "status" TEXT,
    "url" TEXT,
    "nicheTag" TEXT,
    "riskLevel" TEXT,
    "contentComplexity" TEXT,
    "rulesSummary" TEXT,
    "flairRequired" BOOLEAN,
    "requiredFlair" TEXT,
    "totalTests" INTEGER,
    "avg24hViews" FLOAT,
    "removalPct" FLOAT,
    "lastTestedDate" TEXT,
    "subscribers" INTEGER,
    "activeUsers" INTEGER,
    "over18" BOOLEAN
);

CREATE TABLE assets (
    "id" BIGINT PRIMARY KEY,
    "modelId" BIGINT REFERENCES models("id") ON DELETE CASCADE,
    "assetType" TEXT NOT NULL,
    "approved" INTEGER,
    "lastUsedDate" TEXT,
    "driveFileId" TEXT,
    "fileName" TEXT,
    "thumbnailUrl" TEXT,
    "originalUrl" TEXT,
    "angleTag" TEXT,
    "locationTag" TEXT,
    "reuseCooldownSetting" INTEGER,
    "timesUsed" INTEGER,
    "externalUrl" TEXT
);

CREATE TABLE tasks (
    "id" BIGINT PRIMARY KEY,
    "date" TEXT,
    "modelId" BIGINT REFERENCES models("id") ON DELETE CASCADE,
    "accountId" BIGINT REFERENCES accounts("id") ON DELETE CASCADE,
    "subredditId" BIGINT REFERENCES subreddits("id") ON DELETE CASCADE,
    "assetId" BIGINT REFERENCES assets("id") ON DELETE SET NULL,
    "status" TEXT,
    "redditPostId" TEXT,
    "title" TEXT,
    "redditUrl" TEXT,
    "postingWindow" TEXT
);

CREATE TABLE performances (
    "id" BIGINT PRIMARY KEY,
    "taskId" BIGINT REFERENCES tasks("id") ON DELETE CASCADE,
    "views24h" INTEGER,
    "removed" INTEGER,
    "notes" TEXT
);

CREATE TABLE settings (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key" TEXT UNIQUE NOT NULL,
    "value" JSONB
);

-- Seed default settings
INSERT INTO settings ("key", "value") VALUES 
('dailyTestingLimit', '3'::jsonb),
('minViewThreshold', '500'::jsonb),
('testsBeforeClassification', '3'::jsonb),
('removalThresholdPct', '20'::jsonb),
('assetReuseCooldownDays', '30'::jsonb),
('dailyPostCap', '10'::jsonb),
('vaPin', '"1234"'::jsonb)
ON CONFLICT ("key") DO NOTHING;
