-- JS Reddit Growth OS - Supabase Schema
-- Run this in your Supabase SQL Editor

-- 1. Models
CREATE TABLE IF NOT EXISTS models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    primary_niche TEXT,
    weekly_view_target INTEGER DEFAULT 50000,
    weekly_post_target INTEGER DEFAULT 50,
    drive_folder_id TEXT,
    used_folder_id TEXT
);

-- 2. Accounts
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    model_id BIGINT REFERENCES models(id) ON DELETE CASCADE,
    handle TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    daily_cap INTEGER DEFAULT 10,
    cqs_status TEXT,
    removal_rate FLOAT DEFAULT 0,
    notes TEXT
);

-- 3. Subreddits
CREATE TABLE IF NOT EXISTS subreddits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    model_id BIGINT REFERENCES models(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'testing',
    url TEXT,
    niche_tag TEXT,
    risk_level TEXT,
    content_complexity TEXT,
    rules_summary TEXT,
    flair_required BOOLEAN DEFAULT FALSE,
    required_flair TEXT,
    total_tests INTEGER DEFAULT 0,
    avg_24h_views FLOAT DEFAULT 0,
    removal_pct FLOAT DEFAULT 0,
    last_tested_date TIMESTAMP WITH TIME ZONE
);

-- 4. Assets
CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    model_id BIGINT REFERENCES models(id) ON DELETE CASCADE,
    asset_type TEXT NOT NULL, -- 'image' or 'video'
    approved BOOLEAN DEFAULT TRUE,
    last_used_date TIMESTAMP WITH TIME ZONE,
    drive_file_id TEXT,
    file_name TEXT,
    thumbnail_url TEXT,
    original_url TEXT,
    angle_tag TEXT,
    location_tag TEXT,
    reuse_cooldown_setting INTEGER DEFAULT 30,
    times_used INTEGER DEFAULT 0
);

-- 5. Tasks
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    date DATE NOT NULL,
    model_id BIGINT REFERENCES models(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    subreddit_id BIGINT REFERENCES subreddits(id) ON DELETE CASCADE,
    asset_id BIGINT REFERENCES assets(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'generated',
    reddit_post_id TEXT,
    title TEXT,
    posting_window TEXT,
    reddit_url TEXT
);

-- 6. Performances
CREATE TABLE IF NOT EXISTS performances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
    views_24h INTEGER DEFAULT 0,
    removed BOOLEAN DEFAULT FALSE,
    notes TEXT
);

-- 7. Settings (Global configuration)
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB
);

-- Seed default settings
INSERT INTO settings (key, value) VALUES 
('dailyTestingLimit', '3'::jsonb),
('minViewThreshold', '500'::jsonb),
('testsBeforeClassification', '3'::jsonb),
('removalThresholdPct', '20'::jsonb),
('assetReuseCooldownDays', '30'::jsonb),
('dailyPostCap', '10'::jsonb),
('vaPin', '"1234"'::jsonb)
ON CONFLICT (key) DO NOTHING;
